<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LessonSessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lesson_sessions')->insert([
            [
                'number' => 'Upacara',
                'start_time' => '07:00:00',
                'end_time' => '07:40:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '2',
                'start_time' => '07:40:00',
                'end_time' => '08:20:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3',
                'start_time' => '08:20:00',
                'end_time' => '09:00:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4',
                'start_time' => '09:00:00',
                'end_time' => '09:40:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5',
                'start_time' => '10:00:00',
                'end_time' => '10:40:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6',
                'start_time' => '10:40:00',
                'end_time' => '11:20:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '7',
                'start_time' => '11:20:00',
                'end_time' => '12:00:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '8',
                'start_time' => '12:35:00',
                'end_time' => '13:10:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '9',
                'start_time' => '13:10:00',
                'end_time' => '13:45:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '10',
                'start_time' => '13:45:00',
                'end_time' => '14:20:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '11',
                'start_time' => '14:20:00',
                'end_time' => '15:00:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => 'Istirahat-1',
                'start_time' => '09:40:00',
                'end_time' => '10:00:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => 'Istirahat-2',
                'start_time' => '12:00:00',
                'end_time' => '12:35:00',
                'type' => 'monday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '1',
                'start_time' => '07:00:00',
                'end_time' => '07:40:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '2',
                'start_time' => '07:40:00',
                'end_time' => '08:20:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3',
                'start_time' => '08:20:00',
                'end_time' => '09:00:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4',
                'start_time' => '09:00:00',
                'end_time' => '09:40:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5',
                'start_time' => '10:00:00',
                'end_time' => '10:40:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6',
                'start_time' => '10:40:00',
                'end_time' => '11:20:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '7',
                'start_time' => '11:20:00',
                'end_time' => '12:00:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '8',
                'start_time' => '12:35:00',
                'end_time' => '13:10:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '9',
                'start_time' => '13:10:00',
                'end_time' => '13:45:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '10',
                'start_time' => '13:45:00',
                'end_time' => '14:20:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '11',
                'start_time' => '14:20:00',
                'end_time' => '15:00:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => 'Istirahat-1',
                'start_time' => '09:40:00',
                'end_time' => '10:00:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => 'Istirahat-2',
                'start_time' => '12:00:00',
                'end_time' => '12:35:00',
                'type' => 'tuesday-thursday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '1',
                'start_time' => '07:00:00',
                'end_time' => '07:40:00',
                'type' => 'friday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '2',
                'start_time' => '07:40:00',
                'end_time' => '08:20:00',
                'type' => 'friday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3',
                'start_time' => '08:20:00',
                'end_time' => '09:00:00',
                'type' => 'friday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4',
                'start_time' => '09:00:00',
                'end_time' => '09:40:00',
                'type' => 'friday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5',
                'start_time' => '10:00:00',
                'end_time' => '10:35:00',
                'type' => 'friday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6',
                'start_time' => '10:35:00',
                'end_time' => '11:10:00',
                'type' => 'friday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => 'Istirahat-1',
                'start_time' => '09:40:00',
                'end_time' => '10:00:00',
                'type' => 'friday',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
